In [92]:
import numpy as np

In [103]:
ll = np.array([[1,2,3,7,5],[1,2,6,4,5]])

In [104]:
ll.shape

(2, 5)

In [105]:
ll

array([[1, 2, 3, 7, 5],
       [1, 2, 6, 4, 5]])

In [106]:
ll_mean = np.mean(ll, axis=0)
ll_std = np.std(ll, axis=0)

In [107]:
ll_mean

array([1. , 2. , 4.5, 5.5, 5. ])

In [108]:
ll_std

array([0. , 0. , 1.5, 1.5, 0. ])

In [109]:
p = ll-ll_mean

In [111]:
p/ll_std

/Users/teliov/Library/anaconda3/envs/ml/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, nan, -1.,  1., nan],
       [nan, nan,  1., -1., nan]])