In [1]:
# /Users/teliov/TUD/Thesis/Medvice/Notebooks/data/04_06_new_data/data/split
# So we can use the *thesislib* package
import sys
import os

module_path = os.path.abspath("..")

if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import numpy as np
import joblib

In [3]:
nb_clf_file = "/Users/teliov/TUD/Thesis/Medvice/Repo/inference/backend/app/data/nb_clf.joblib"

In [4]:
nb_data = joblib.load(nb_clf_file)

In [5]:
nb_clf = nb_data.get("clf")

In [6]:
vector = np.zeros(3 + 33).reshape(1, -1)

In [7]:
from scipy.sparse import csc_matrix

In [8]:
vector = csc_matrix(vector)

In [9]:
prediction = nb_clf.predict_proba(vector)

In [25]:
sorted_ = np.argsort(prediction)

In [27]:
top_5 = sorted_[0, -5:][::-1]

In [33]:
print(prediction[0, top_5])
print(top_5)

[0.8062548  0.09561769 0.07118041 0.01301221 0.00745225]
[6 7 2 5 9]


In [31]:
rf_clf_file = "/Users/teliov/TUD/Thesis/Medvice/Repo/inference/backend/app/data/rf_clf.joblib"
rf_clf_data = joblib.load(rf_clf_file)
rf_clf = rf_clf_data.get("clf")

In [32]:
rf_prediction = rf_clf.predict_proba(vector)

In [34]:
rf_sorted_ = np.argsort(rf_prediction)
rf_top_5 = rf_sorted_[0, -5:][::-1]
print(rf_prediction[0, rf_top_5])
print(rf_top_5)

[0.32065232 0.15959197 0.12117845 0.11460733 0.10991171]
[ 6  7 13 10  2]


In [35]:
top_5

array([6, 7, 2, 5, 9])

In [36]:
import json
cnd_file = "/Users/teliov/TUD/Thesis/Medvice/Repo/inference/backend/app/data/condition_db.json"
with open (cnd_file) as fp:
    cnd = json.load(fp)

In [37]:
cnd_rev = {val:key for key, val in cnd.items()}

In [38]:
list(cnd.keys())[6]

'tension_type_headache'